"""核心基础设施 — 异常层级 + 模型路由"""

from .exceptions import (
    AgentConstraintViolation,
    AgentDecisionError,
    AgentError,
    AoqiweiAPIError,
    BusinessRuleError,
    CacheConnectionError,
    DataValidationError,
    ExternalAPIError,
    FeishuWebhookError,
    FoodSafetyError,
    InfrastructureError,
    MarginViolationError,
    MeituanAPIError,
    ModelRouterError,
    PinzhiAPIError,
    POSAdapterError,
    ReconciliationMismatchError,
    SMSServiceError,
    ServiceTimeoutError,
    TenantIsolationError,
    TunxiangBaseError,
    VectorDBError,
    WeComWebhookError,
)
from .model_router import ModelRouter, TaskComplexity, model_router

__all__ = [
    # 异常层级
    "TunxiangBaseError",
    "ExternalAPIError",
    "POSAdapterError",
    "PinzhiAPIError",
    "AoqiweiAPIError",
    "MeituanAPIError",
    "WeComWebhookError",
    "FeishuWebhookError",
    "SMSServiceError",
    "DataValidationError",
    "ReconciliationMismatchError",
    "TenantIsolationError",
    "BusinessRuleError",
    "MarginViolationError",
    "FoodSafetyError",
    "ServiceTimeoutError",
    "InfrastructureError",
    "CacheConnectionError",
    "VectorDBError",
    "ModelRouterError",
    "AgentError",
    "AgentDecisionError",
    "AgentConstraintViolation",
    # 模型路由
    "TaskComplexity",
    "ModelRouter",
    "model_router",
]
