#!/bin/bash
# Tailscale 自动安装与配置脚本
# 用途：门店 Mac mini / 云端 Linux 服务器自动接入 Tailscale 网络
#
# 使用方式：
#   TAILSCALE_AUTH_KEY=tskey-auth-xxx STORE_ID=store-001 bash tailscale-config.sh
#
# 环境变量：
#   TAILSCALE_AUTH_KEY — Tailscale auth key（必需）
#   STORE_ID          — 门店编号（必需，用于 MagicDNS 主机名）
#   TXOS_ALLOWED_PORTS — 允许的端口（默认 8000,8100）

set -euo pipefail

# ── 参数校验 ──

TAILSCALE_AUTH_KEY="${TAILSCALE_AUTH_KEY:?Error: TAILSCALE_AUTH_KEY is required}"
STORE_ID="${STORE_ID:?Error: STORE_ID is required}"
ALLOWED_PORTS="${TXOS_ALLOWED_PORTS:-8000,8100}"

echo "=== TunxiangOS Tailscale Configuration ==="
echo "Store ID: ${STORE_ID}"
echo "Allowed ports: ${ALLOWED_PORTS}"
echo ""

# ── 检测操作系统 ──

detect_os() {
    case "$(uname -s)" in
        Darwin)
            echo "macos"
            ;;
        Linux)
            echo "linux"
            ;;
        *)
            echo "unsupported"
            ;;
    esac
}

OS_TYPE=$(detect_os)
echo "Detected OS: ${OS_TYPE}"

if [ "${OS_TYPE}" = "unsupported" ]; then
    echo "Error: Unsupported operating system $(uname -s)"
    exit 1
fi

# ── 安装 Tailscale ──

install_tailscale_macos() {
    if command -v tailscale &>/dev/null; then
        echo "Tailscale already installed ($(tailscale version 2>/dev/null || echo 'unknown version'))"
        return 0
    fi

    echo "Installing Tailscale via Homebrew..."
    if ! command -v brew &>/dev/null; then
        echo "Error: Homebrew is required on macOS. Install from https://brew.sh"
        exit 1
    fi

    brew install tailscale
    echo "Tailscale installed successfully."
}

install_tailscale_linux() {
    if command -v tailscale &>/dev/null; then
        echo "Tailscale already installed ($(tailscale version 2>/dev/null || echo 'unknown version'))"
        return 0
    fi

    echo "Installing Tailscale via official script..."

    # 使用 Tailscale 官方安装脚本
    curl -fsSL https://tailscale.com/install.sh | sh

    # 启动 tailscaled 服务
    if command -v systemctl &>/dev/null; then
        sudo systemctl enable --now tailscaled
    else
        echo "Warning: systemd not found, please start tailscaled manually"
    fi

    echo "Tailscale installed successfully."
}

if [ "${OS_TYPE}" = "macos" ]; then
    install_tailscale_macos
else
    install_tailscale_linux
fi

# ── 连接 Tailscale 网络 ──

echo ""
echo "Connecting to Tailscale network..."

# 设置主机名为 store-xxx 格式，实现 MagicDNS 访问 store-xxx.ts.net
HOSTNAME="${STORE_ID}"

if [ "${OS_TYPE}" = "macos" ]; then
    # macOS: 通过 Tailscale.app 或 CLI
    sudo tailscale up \
        --authkey="${TAILSCALE_AUTH_KEY}" \
        --hostname="${HOSTNAME}" \
        --accept-routes \
        --accept-dns
else
    # Linux
    sudo tailscale up \
        --authkey="${TAILSCALE_AUTH_KEY}" \
        --hostname="${HOSTNAME}" \
        --accept-routes \
        --accept-dns
fi

echo "Tailscale connected. Hostname: ${HOSTNAME}"
echo "MagicDNS address: ${HOSTNAME}.ts.net"

# 获取 Tailscale IP
TS_IP=$(tailscale ip -4 2>/dev/null || echo "unknown")
echo "Tailscale IPv4: ${TS_IP}"

# ── 配置防火墙规则 ──

echo ""
echo "Configuring firewall rules (allow ports: ${ALLOWED_PORTS})..."

configure_firewall_macos() {
    # macOS: 使用 pf (Packet Filter)
    PF_RULES_FILE="/etc/pf.anchors/tunxiang-tailscale"

    # 获取 Tailscale 接口名称
    TS_INTERFACE=$(ifconfig | grep -B1 "inet ${TS_IP}" | head -1 | cut -d: -f1 2>/dev/null || echo "utun")

    echo "Creating pf rules for Tailscale interface..."

    # 生成 pf 规则文件
    sudo tee "${PF_RULES_FILE}" > /dev/null << PFRULES
# TunxiangOS Tailscale firewall rules
# Only allow specified ports on Tailscale interface
# Generated by tailscale-config.sh

# Block all incoming on Tailscale interface by default
block in on ${TS_INTERFACE} all

# Allow established connections
pass in on ${TS_INTERFACE} proto tcp from any to any flags A/A

# Allow specified ports
$(IFS=','; for port in ${ALLOWED_PORTS}; do
    echo "pass in on ${TS_INTERFACE} proto tcp from any to any port ${port}"
done)

# Allow ICMP (ping) for health checks
pass in on ${TS_INTERFACE} proto icmp all
PFRULES

    # 检查 pf 主配置中是否已包含 anchor
    if ! grep -q "tunxiang-tailscale" /etc/pf.conf 2>/dev/null; then
        echo ""
        echo "[INFO] To activate firewall rules, add the following to /etc/pf.conf:"
        echo "  anchor \"tunxiang-tailscale\""
        echo "  load anchor \"tunxiang-tailscale\" from \"${PF_RULES_FILE}\""
        echo "Then run: sudo pfctl -ef /etc/pf.conf"
    fi

    echo "macOS pf rules written to ${PF_RULES_FILE}"
}

configure_firewall_linux() {
    # Linux: 使用 iptables
    if ! command -v iptables &>/dev/null; then
        echo "Warning: iptables not found, skipping firewall configuration"
        return 0
    fi

    # 获取 Tailscale 接口
    TS_INTERFACE="tailscale0"

    echo "Configuring iptables rules for interface ${TS_INTERFACE}..."

    # 清除旧的 tunxiang 规则链（如果存在）
    sudo iptables -D INPUT -i "${TS_INTERFACE}" -j TXOS_TAILSCALE 2>/dev/null || true
    sudo iptables -F TXOS_TAILSCALE 2>/dev/null || true
    sudo iptables -X TXOS_TAILSCALE 2>/dev/null || true

    # 创建自定义链
    sudo iptables -N TXOS_TAILSCALE

    # 允许已建立的连接
    sudo iptables -A TXOS_TAILSCALE -m state --state ESTABLISHED,RELATED -j ACCEPT

    # 允许指定端口
    IFS=',' read -ra PORTS <<< "${ALLOWED_PORTS}"
    for port in "${PORTS[@]}"; do
        sudo iptables -A TXOS_TAILSCALE -p tcp --dport "${port}" -j ACCEPT
        echo "  Allowed TCP port ${port}"
    done

    # 允许 ICMP
    sudo iptables -A TXOS_TAILSCALE -p icmp -j ACCEPT

    # 拒绝其他流量
    sudo iptables -A TXOS_TAILSCALE -j DROP

    # 将自定义链挂到 INPUT
    sudo iptables -A INPUT -i "${TS_INTERFACE}" -j TXOS_TAILSCALE

    # 持久化规则
    if command -v iptables-save &>/dev/null; then
        sudo iptables-save > /etc/iptables/rules.v4 2>/dev/null || \
        sudo sh -c "iptables-save > /etc/iptables.rules" 2>/dev/null || true
        echo "iptables rules saved."
    fi

    echo "Linux iptables rules configured for ${TS_INTERFACE}"
}

if [ "${OS_TYPE}" = "macos" ]; then
    configure_firewall_macos
else
    configure_firewall_linux
fi

# ── 验证连接 ──

echo ""
echo "=== Verifying Tailscale Connection ==="

tailscale status

echo ""
echo "=== Configuration Complete ==="
echo ""
echo "Summary:"
echo "  Store ID:     ${STORE_ID}"
echo "  MagicDNS:     ${HOSTNAME}.ts.net"
echo "  Tailscale IP: ${TS_IP}"
echo "  Allowed ports: ${ALLOWED_PORTS}"
echo ""
echo "Other devices can now reach this machine at:"
echo "  http://${HOSTNAME}.ts.net:8000  (Mac Station API)"
echo "  http://${HOSTNAME}.ts.net:8100  (Core ML Bridge)"
echo ""
echo "To verify from another Tailscale node:"
echo "  curl http://${HOSTNAME}.ts.net:8000/health"
