"""预警规则注册表 -- 30+ 条预置规则覆盖全部业务域"""
from __future__ import annotations
from .models import AlertRule, AlertSeverity

DEFAULT_ALERT_RULES: list[AlertRule] = [
    AlertRule(rule_id="sales_drop_20pct", name="销售额同比下降超20%", domain="sales", severity=AlertSeverity.P1_IMPORTANT, metric_field="total_revenue_fen", condition="decrease_pct > threshold", threshold=20.0, notify_roles=["store_manager","ops"], notify_channels=["in_app","wechat"], auto_escalation_minutes=240, escalate_to_roles=["ceo"]),
    AlertRule(rule_id="sales_3day_continuous_decline", name="连续3天销售额下降", domain="sales", severity=AlertSeverity.P0_CRITICAL, metric_field="total_revenue_fen", condition="continuous_decline_days >= threshold", threshold=3.0, notify_roles=["store_manager","ops","ceo"], notify_channels=["in_app","wechat","sms"], auto_escalation_minutes=60, escalate_to_roles=["ceo"]),
    AlertRule(rule_id="sales_target_below_70", name="月度目标完成率<70%", domain="sales", severity=AlertSeverity.P1_IMPORTANT, metric_field="month_completion_pct", condition="completion_pct < threshold", threshold=70.0, lookback_period="30d", cooldown_minutes=1440, notify_roles=["store_manager","ops","ceo"], notify_channels=["in_app","wechat"]),
    AlertRule(rule_id="sales_avg_ticket_anomaly", name="客单价异常波动", domain="sales", severity=AlertSeverity.P2_NORMAL, metric_field="avg_ticket_fen", condition="abs(deviation_pct) > threshold", threshold=15.0, lookback_period="7d", cooldown_minutes=240, notify_roles=["store_manager"], notify_channels=["in_app"]),
    AlertRule(rule_id="sales_customer_count_drop_25pct", name="客流同比下降超25%", domain="sales", severity=AlertSeverity.P1_IMPORTANT, metric_field="customer_count", condition="decrease_pct > threshold", threshold=25.0, notify_roles=["store_manager","ops"], notify_channels=["in_app","wechat"]),
    AlertRule(rule_id="dish_return_rate_10pct", name="菜品退货率超10%", domain="dish", severity=AlertSeverity.P1_IMPORTANT, metric_field="return_rate_pct", condition="return_rate > threshold", threshold=10.0, notify_roles=["store_manager","ops","chef"], notify_channels=["in_app","wechat"]),
    AlertRule(rule_id="dish_margin_contribution_decline", name="菜品毛利贡献率下降", domain="dish", severity=AlertSeverity.P2_NORMAL, metric_field="margin_contribution_pct", condition="decrease_pct > threshold", threshold=10.0, lookback_period="7d", cooldown_minutes=720, notify_roles=["store_manager","chef"], notify_channels=["in_app"]),
    AlertRule(rule_id="dish_slow_moving_7day", name="菜品滞销预警（7天）", domain="dish", severity=AlertSeverity.P2_NORMAL, metric_field="daily_sales_qty", condition="avg_7day < baseline_avg * 0.5", threshold=0.5, lookback_period="7d", cooldown_minutes=1440, notify_roles=["store_manager","chef"], notify_channels=["in_app"]),
    AlertRule(rule_id="dish_negative_margin_accumulating", name="菜品累计亏损增加", domain="dish", severity=AlertSeverity.P1_IMPORTANT, metric_field="total_margin_fen", condition="margin < 0", threshold=0.0, lookback_period="7d", cooldown_minutes=720, notify_roles=["store_manager","ops"], notify_channels=["in_app","wechat"]),
    AlertRule(rule_id="member_churn_rate_15pct", name="会员流失率超15%", domain="member", severity=AlertSeverity.P0_CRITICAL, metric_field="churn_rate_pct", condition="churn_pct > threshold", threshold=15.0, lookback_period="30d", cooldown_minutes=1440, notify_roles=["ops","ceo"], notify_channels=["in_app","wechat","sms"], auto_escalation_minutes=120, escalate_to_roles=["ceo"]),
    AlertRule(rule_id="member_repurchase_rate_drop", name="复购率连续下降", domain="member", severity=AlertSeverity.P1_IMPORTANT, metric_field="repurchase_rate_pct", condition="decrease_pp > threshold", threshold=5.0, lookback_period="14d", cooldown_minutes=1440, notify_roles=["ops","ceo"], notify_channels=["in_app","wechat"]),
    AlertRule(rule_id="member_stored_value_anomaly", name="储值余额异常波动", domain="member", severity=AlertSeverity.P2_NORMAL, metric_field="stored_value_balance_change_fen", condition="abs(z_score) > threshold", threshold=2.0, lookback_period="30d", cooldown_minutes=360, notify_roles=["ops"], notify_channels=["in_app"]),
    AlertRule(rule_id="member_vip_dormant_30day", name="VIP客户超30天未消费", domain="member", severity=AlertSeverity.P2_NORMAL, metric_field="dormant_days", condition="dormant_days > threshold", threshold=30.0, lookback_period="30d", cooldown_minutes=720, notify_roles=["ops","store_manager"], notify_channels=["in_app"]),
    AlertRule(rule_id="cost_food_rate_45pct", name="食材成本率超45%", domain="cost", severity=AlertSeverity.P1_IMPORTANT, metric_field="food_cost_rate_pct", condition="cost_rate > threshold", threshold=45.0, notify_roles=["store_manager","ops","ceo"], notify_channels=["in_app","wechat"], auto_escalation_minutes=240, escalate_to_roles=["ceo"]),
    AlertRule(rule_id="cost_labor_rate_25pct", name="人工成本率超25%", domain="cost", severity=AlertSeverity.P1_IMPORTANT, metric_field="labor_cost_rate_pct", condition="cost_rate > threshold", threshold=25.0, notify_roles=["store_manager","ops"], notify_channels=["in_app","wechat"]),
    AlertRule(rule_id="cost_waste_rate_5pct", name="损耗率超5%", domain="cost", severity=AlertSeverity.P1_IMPORTANT, metric_field="waste_rate_pct", condition="waste_rate > threshold", threshold=5.0, notify_roles=["store_manager","chef"], notify_channels=["in_app","wechat"]),
    AlertRule(rule_id="cost_total_rate_70pct", name="综合成本率超70%", domain="cost", severity=AlertSeverity.P0_CRITICAL, metric_field="total_cost_rate_pct", condition="cost_rate > threshold", threshold=70.0, notify_roles=["store_manager","ops","ceo"], notify_channels=["in_app","wechat","sms"], auto_escalation_minutes=60, escalate_to_roles=["ceo"]),
    AlertRule(rule_id="supply_inventory_turnover_30day", name="库存周转超30天", domain="supply", severity=AlertSeverity.P2_NORMAL, metric_field="inventory_turnover_days", condition="turnover_days > threshold", threshold=30.0, cooldown_minutes=1440, notify_roles=["store_manager","procurement"], notify_channels=["in_app"]),
    AlertRule(rule_id="supply_stockout_risk", name="缺货风险预警", domain="supply", severity=AlertSeverity.P0_CRITICAL, metric_field="days_of_supply", condition="days_of_supply < threshold", threshold=2.0, cooldown_minutes=60, notify_roles=["store_manager","procurement","chef"], notify_channels=["in_app","wechat","sms"], auto_escalation_minutes=60, escalate_to_roles=["ops","ceo"]),
    AlertRule(rule_id="supply_expiry_3day", name="效期不足3天预警", domain="supply", severity=AlertSeverity.P1_IMPORTANT, metric_field="days_until_expiry", condition="days_until_expiry <= threshold", threshold=3.0, notify_roles=["store_manager","chef","procurement"], notify_channels=["in_app","wechat"]),
    AlertRule(rule_id="supply_price_spike_20pct", name="采购价格上涨超20%", domain="supply", severity=AlertSeverity.P1_IMPORTANT, metric_field="unit_price_fen", condition="price_increase_pct > threshold", threshold=20.0, lookback_period="7d", cooldown_minutes=720, notify_roles=["procurement","ops"], notify_channels=["in_app","wechat"]),
    AlertRule(rule_id="finance_gross_margin_anomaly", name="毛利率异常", domain="finance", severity=AlertSeverity.P0_CRITICAL, metric_field="gross_margin_pct", condition="margin < target - threshold", threshold=10.0, notify_roles=["store_manager","ops","ceo"], notify_channels=["in_app","wechat","sms"], auto_escalation_minutes=120, escalate_to_roles=["ceo"]),
    AlertRule(rule_id="finance_cashflow_negative", name="现金流为负预警", domain="finance", severity=AlertSeverity.P0_CRITICAL, metric_field="net_cashflow_fen", condition="net_cashflow < threshold", threshold=0.0, lookback_period="30d", cooldown_minutes=720, notify_roles=["ceo","ops"], notify_channels=["in_app","wechat","sms"], auto_escalation_minutes=60, escalate_to_roles=["ceo"]),
    AlertRule(rule_id="finance_budget_overrun_10pct", name="预算超支超10%", domain="finance", severity=AlertSeverity.P1_IMPORTANT, metric_field="budget_overrun_pct", condition="overrun_pct > threshold", threshold=10.0, lookback_period="30d", cooldown_minutes=720, notify_roles=["ops","ceo"], notify_channels=["in_app","wechat"]),
    AlertRule(rule_id="finance_receivable_overdue", name="应收账款逾期超7天", domain="finance", severity=AlertSeverity.P2_NORMAL, metric_field="overdue_days", condition="overdue_days > threshold", threshold=7.0, cooldown_minutes=1440, notify_roles=["ops"], notify_channels=["in_app"]),
    AlertRule(rule_id="store_bad_review_rate_5pct", name="差评率超5%", domain="store", severity=AlertSeverity.P1_IMPORTANT, metric_field="bad_review_rate_pct", condition="bad_rate > threshold OR bad_count > 3", threshold=5.0, notify_roles=["store_manager","ops"], notify_channels=["in_app","wechat"], auto_escalation_minutes=240, escalate_to_roles=["ceo"]),
    AlertRule(rule_id="store_turnover_rate_low", name="翻台率低于1.5", domain="store", severity=AlertSeverity.P2_NORMAL, metric_field="turnover_rate", condition="turnover_rate < threshold", threshold=1.5, cooldown_minutes=240, notify_roles=["store_manager"], notify_channels=["in_app"]),
    AlertRule(rule_id="store_area_efficiency_drop", name="坪效连续下降", domain="store", severity=AlertSeverity.P2_NORMAL, metric_field="revenue_per_sqm_fen", condition="revenue_per_sqm < baseline * 0.85", threshold=0.85, lookback_period="7d", cooldown_minutes=1440, notify_roles=["store_manager","ops"], notify_channels=["in_app"]),
    AlertRule(rule_id="store_table_idle_rate_high", name="桌台空闲率过高", domain="store", severity=AlertSeverity.P2_NORMAL, metric_field="table_idle_rate_pct", condition="idle_rate > threshold", threshold=40.0, notify_roles=["store_manager"], notify_channels=["in_app"]),
]
RULES_BY_DOMAIN: dict = {}
for _r in DEFAULT_ALERT_RULES:
    RULES_BY_DOMAIN.setdefault(_r.domain, []).append(_r)
RULES_BY_ID = {r.rule_id: r for r in DEFAULT_ALERT_RULES}
